services:
  web:
    build: .
    command: gunicorn digitallibrary.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      - DATABASE_URL=mysql://admin:Kn@22112005@db:3306/digital_library_data_2
      - CELERY_BROKER_URL=amqp://root:@pPN&E&6nib7m8xp@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=django-db
    entrypoint: ["/web_entrypoint.sh"]

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'digital_library_data_2'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'Kn@22112005'
      MYSQL_ROOT_PASSWORD: '@pPN&E&6nib7m8xp'
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: '@pPN&E&6nib7m8xp'
    ports:
      - "5673:5672"
      - "15673:15672"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A digitallibrary worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      - DATABASE_URL=mysql://admin:Kn@22112005@db:3306/digital_library_data_2
      - CELERY_BROKER_URL=amqp://root:@pPN&E&6nib7m8xp@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=django-db

  beat:
    build: .
    command: celery -A digitallibrary beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      - DATABASE_URL=mysql://admin:Kn@22112005@db:3306/digital_library_data_2
      - CELERY_BROKER_URL=amqp://root:@pPN&E&6nib7m8xp@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=django-db
