# Generated by Django 5.0.6 on 2024-06-12 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books_db', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'department__in': ['WK', 'IT']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_db.book'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.reader'),
        ),
        migrations.AddField(
            model_name='fine',
            name='collector',
            field=models.ForeignKey(limit_choices_to={'department__in': ['TR', 'IT']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.reader'),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_db.book'),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'department__in': ['LI', 'IT']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.reader'),
        ),
        migrations.AddField(
            model_name='removalreport',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books_db.book'),
        ),
        migrations.AddField(
            model_name='removalreport',
            name='remover',
            field=models.ForeignKey(limit_choices_to={'department': 'WK'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='borrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_db.borrow'),
        ),
        migrations.AddField(
            model_name='return',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.reader'),
        ),
    ]
