# Generated by Django 5.0.6 on 2024-06-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_db', '0004_borrow_request_date_alter_borrow_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
