# Generated by Django 5.0.6 on 2024-07-05 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_db', '0006_book_language'),
        ('users', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=12, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books', models.ManyToManyField(related_name='book_lists', to='books_db.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_lists', to='users.reader')),
            ],
            options={
                'unique_together': {('user', 'slug')},
            },
        ),
    ]
