# Generated by Django 5.0.6 on 2024-07-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_db', '0007_alter_book_value_booklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='ready_made',
            field=models.BooleanField(default=False),
        ),
    ]
