# Generated by Django 5.0.6 on 2024-07-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_db', '0011_alter_book_id_alter_booklist_id_alter_borrow_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='booklist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booklist',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lostreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lostreport',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='removalreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='removalreport',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='return',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='return',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lostreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='removalreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='return',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
