# Generated by Django 5.0.6 on 2024-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_db', '0005_alter_borrow_due_date'),
        ('users', '0002_alter_reader_borrowed_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, related_name='borrowed_books', to='books_db.borrow'),
        ),
    ]
